### ISSUE TITLE
Zou jij mijn verslag in de hanze organisatie repository willen zetten? 

### ISSUE THREAD

**Issue by DDJager** [RobinvanEijk/BoggleOpgave#3]
Zie titel

**Comment by RobinvanEijk** [comment]
Prima! Staat die nu in de boggleSort opgave?

Op 23 mrt. 2017 10:52 p.m. schreef Danny Jager <notifications@github.com>:

Zie titel

**Comment by DDJager** [comment]
Yup. Docx bestand. Ik heb geen rechten om te pushen in de andere repo.

**Comment by RobinvanEijk** [comment]
gedaan
